name: Land
version: 1.0
main: Land.LandMain
api-version: 1.19
authors: [ Gnaris ]
depend: [SP_Database, GroupManager, Economy]
commands:
  spland:
  land:
permission:
  sperias.land.claim.modify:
    description: "Peut tout faire sur les terrains des joueurs"
  sperias.land.command.staff:
    description: "Claim ou voir des terrains de staff"
